micronaut:
  application:
    name: first.application
otel:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      endpoint: https://otlp.eu01.nr-data.net:4317
      headers: api-key=${NEW_RELIC_KEY}
      compression: gzip
      key: ${NEW_RELIC_KEY}
      instance: ${random.shortuuid}
    experimental:
      expoter:
        otlp:
          retry:
            enabled: true
    metric:
      export:
        interval: 5000
netty:
  default:
    allocator:
      max-order: 3
